name: Bump Version

on: workflow_dispatch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - run: git config --global user.email "github-actions@example.com"
      - run: git config --global user.name "GitHub Actions"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Npm Version Minor
        run: npm version minor

      - name: Git Push
        run: git push origin main --tags
#      - uses: actions/upload-artifact@v2
#        with:
#          name: src
#          path: ./