name: "on-push-check-and-publish-package"
on:
  push:
    branches:
      - main

jobs:
  check-and-publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
#          registry-url: 'https://npm.pkg.github.com'
#          scope: '@martin-dsp'
      - name: Install Dependencies
        run: npm install

      - name: Publish Package
        run: npm publish --registry https://registry.npmjs.org --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - run: npm test
#      - uses: JS-DevTools/npm-publish@v1
#        with:
#          token: ${{ secrets.NPM_TOKEN }}
#          registry: "https://npm.pkg.github.com"